# Generated by Django 5.2.4 on 2025-09-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.82, help_text='Discount multiplier (e.g., 0.82 for 18% off)'),
        ),
    ]
