# Generated by Django 5.2.4 on 2025-09-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_flavor_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flavor',
            new_name='flavour',
        ),
    ]
